name: Deploying Medusa Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production
    

    steps:
      - name: Checking out the code
        uses: actions/checkout@v3

      - name: Configuring AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Logging in to AWS ECR
        run: aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
        

      - name: Building Docker image
        run: docker build -f ./dockerfile -t medusa-backend ./medusa-backend

      - name: Tagging Docker image
        run: docker tag medusa-backend:latest public.ecr.aws/v7f0w4r6/medusa-backend:latest

      - name: Pushing Docker image
        run: docker push public.ecr.aws/v7f0w4r6/medusa-backend:latest

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve
